---
- name: Install nginx and dependencies
  ansible.builtin.package:
    name:
      - nginx
      - libnginx-mod-http-headers-more-filter
      - unzip
    state: present

- name: Install ModSecurity WAF
  ansible.builtin.package:
    name:
      - libnginx-mod-http-modsecurity
      - modsecurity-crs
    state: present
  when: nginx_waf_install
