---
- name: Configure stub_status for Nginx internals
  ansible.builtin.template:
    src: metrics.conf.j2
    dest: /etc/nginx/conf.d/metrics.conf
    mode: '0644'
  notify: Reload nginx

- name: Create nginx_exporter system user
  ansible.builtin.user:
    name: nginx_exporter
    system: true
    shell: /sbin/nologin
    state: present

- name: Install nginx_exporter via remote_asset role
  ansible.builtin.include_role:
    name: ahmz.server_setup.asset
  vars:
    asset_name: "nginx-prometheus-exporter"
    asset_version: "{{ nginx_exporter_version }}"
    asset_url: "github.com/nginxinc/nginx-prometheus-exporter/releases/download/v%v/nginx-prometheus-exporter_%v_linux_amd64.tar.gz"
    asset_extract: true
    asset_extract_src: "nginx-prometheus-exporter"
    asset_version_cmd: "--version"
    asset_version_regex: 'version\s+([0-9.]+)'
    asset_service_stop: "nginx_exporter"
    asset_download_locally: "{{ nginx_download_locally | default(false) }}"
    asset_register_path_var: "nginx_exporter_bin_path"

- name: Configure nginx_exporter systemd service
  ansible.builtin.template:
    src: nginx_exporter.service.j2
    dest: /etc/systemd/system/nginx_exporter.service
    mode: '0644'
  notify:
    - "systemd daemon-reload"
    - Restart nginx_exporter

- name: Enable and start nginx_exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: "{{ 'started' if nginx_exporter_enabled | default(false) else 'stopped' }}"
    enabled: "{{ nginx_exporter_enabled | default(false) }}"
    daemon_reload: true
