---
- name: Create promtail system user
  ansible.builtin.user:
    name: promtail
    system: true
    shell: /sbin/nologin
    groups: adm
    append: true
    state: present

- name: Install promtail via remote_asset role
  ansible.builtin.include_role:
    name: ahmz.server_setup.asset
  vars:
    asset_name: "promtail"
    asset_version: "{{ nginx_promtail_version }}"
    asset_url: "github.com/grafana/loki/releases/download/v%v/promtail-linux-amd64.zip"
    asset_extract: true
    asset_extract_src: "promtail-linux-amd64"
    asset_version_cmd: "--version"
    asset_version_regex: 'promtail,\s+version\s+([0-9.]+)'
    asset_service_stop: "promtail"
    asset_download_locally: "{{ nginx_download_locally | default(false) }}"
    asset_register_path_var: "nginx_promtail_bin_path"

- name: Ensure promtail config directory exists
  ansible.builtin.file:
    path: /etc/promtail
    state: directory
    mode: '0755'

- name: Configure promtail
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: /etc/promtail/config.yml
    mode: '0644'
  notify: Restart promtail

- name: Configure promtail systemd service
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    mode: '0644'
  notify:
    - "systemd daemon-reload"
    - Restart promtail

- name: Enable and start promtail
  ansible.builtin.systemd:
    name: promtail
    state: "{{ 'started' if nginx_promtail_enabled | default(false) else 'stopped' }}"
    enabled: "{{ nginx_promtail_enabled | default(false) }}"
    daemon_reload: true
