---
- name: Ensure modsecurity directory exists
  ansible.builtin.file:
    path: /etc/modsecurity
    state: directory
    mode: '0755'

- name: Install modsecurity recommended config via remote_asset
  ansible.builtin.include_role:
    name: ahmz.server_setup.asset
  vars:
    asset_name: "modsec-conf"
    asset_type: "file"
    asset_version: "3.0.0"
    asset_url: "raw.githubusercontent.com/owasp-modsecurity/ModSecurity/v3/master/modsecurity.conf-recommended"
    asset_dest: "/etc/modsecurity/modsecurity.conf-recommended"
    asset_extract: false
    asset_download_locally: "{{ nginx_download_locally | default(false) }}"

- name: Install unicode mapping file via remote_asset
  ansible.builtin.include_role:
    name: ahmz.server_setup.asset
  vars:
    asset_name: "unicode-mapping"
    asset_type: "file"
    asset_version: "3.0.0"
    asset_url: "raw.githubusercontent.com/owasp-modsecurity/ModSecurity/v3/master/unicode.mapping"
    asset_dest: "/etc/modsecurity/unicode.mapping"
    asset_extract: false
    asset_download_locally: "{{ nginx_download_locally | default(false) }}"

- name: Initialize modsecurity config
  ansible.builtin.copy:
    src: /etc/modsecurity/modsecurity.conf-recommended
    dest: /etc/modsecurity/modsecurity.conf
    remote_src: true
    force: false
    mode: '0644'
  notify: Reload nginx

- name: Configure global modsecurity settings
  ansible.builtin.lineinfile:
    path: /etc/modsecurity/modsecurity.conf
    regexp: '^\s*(#\s*)?{{ item.key }}\s+.*$'
    line: '{{ item.key }} {{ item.value }}'
  loop: "{{ nginx_waf_global_settings | dict2items }}"
  notify: Reload nginx

- name: Install CRS setup config via remote_asset
  ansible.builtin.include_role:
    name: ahmz.server_setup.asset
    apply:
      notify: Reload nginx
  vars:
    asset_name: "crs-setup"
    asset_type: "file"
    asset_version: "3.3.0"
    asset_url: "raw.githubusercontent.com/coreruleset/coreruleset/v3.3/master/crs-setup.conf.example"
    asset_dest: "/etc/modsecurity/crs-setup.conf"
    asset_extract: false
    asset_download_locally: "{{ nginx_download_locally | default(false) }}"

- name: Create nginx modsec directory
  ansible.builtin.file:
    path: /etc/nginx/modsec
    state: directory
    mode: '0755'

- name: Configure modsec main inclusion
  ansible.builtin.template:
    src: modsec_main.conf.j2
    dest: /etc/nginx/modsec/main.conf
    mode: '0644'
  notify: Reload nginx
