---
galaxy_info:
  role_name: asset
  author: AHMZ
  description: >-
    Universal utility role to check, download, and install/update
    remote assets including standalone binaries, single files, or extracted directories.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: [focal, jammy, noble]
    - name: Debian
      versions: [bullseye, bookworm]
    - name: EL
      versions: ["8", "9"]
  galaxy_tags:
    - utility
    - installer
    - downloader

dependencies: []
