---
- import_tasks: singbox.yml
  when: node_singbox_install
- import_tasks: tools.yml
- import_tasks: gost.yml
  when: node_gost_install
- import_tasks: docker.yml
  when: node_docker_enabled
- import_tasks: nginx.yml
  when: node_nginx_enabled
