---
- name: Restart singbox
  ansible.builtin.systemd:
    name: sing-box
    state: restarted
    daemon_reload: true
  when: node_singbox_enabled

- name: Restart gost
  ansible.builtin.systemd:
    name: gost
    state: restarted
    daemon_reload: true
  when: node_gost_enabled

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
  when: node_exporter_enabled

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  when: node_docker_enabled
