---
- name: Validate, prepare and login registries
  ansible.builtin.include_tasks: prepare.yml
  tags: [apps, ci-cd, deploy]

- name: Provision Docker networks
  ansible.builtin.include_tasks: network.yml
  tags: [apps, ci-cd, deploy]

- name: Deploy containers
  ansible.builtin.include_tasks: deploy.yml
  tags: [apps, ci-cd, deploy]

- name: Prune unmanaged resources
  ansible.builtin.include_tasks: prune.yml
  when: (apps_prune | default({})).enabled | default(false) | bool
  tags: [apps, apps-prune]
