---
- name: Create node_exporter system user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /sbin/nologin
    state: present

- name: Install/Update node_exporter via remote_asset role
  ansible.builtin.include_role:
    name: ahmz.server_setup.asset
  vars:
    asset_name: "node_exporter"
    asset_version: "{{ node_exporter_version }}"
    asset_url: "github.com/prometheus/node_exporter/releases/download/v%v/node_exporter-%v.linux-amd64.tar.gz"
    asset_extract: true
    asset_extract_src: "node_exporter-%v.linux-amd64/node_exporter"
    asset_version_cmd: "--version"
    asset_version_regex: 'version\s+([0-9.]+)'
    asset_service_stop: "node_exporter"
    asset_download_locally: "{{ node_download_locally | default(false) }}"
    asset_register_path_var: "node_exporter_bin_path"

- name: Configure node_exporter systemd service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify:
    - "systemd daemon-reload"
    - Restart node_exporter

- name: Manage node_exporter service state
  ansible.builtin.systemd:
    name: node_exporter
    state: "{{ node_exporter_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ node_exporter_enabled }}"
    daemon_reload: true
